# Generated by Django 5.0.6 on 2024-05-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_remove_profile_user_delete_video_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.TextField()),
                ('fitnessgoal', models.TextField()),
                ('meal_plan', models.JSONField()),
            ],
        ),
    ]
