# Generated by Django 5.0.6 on 2024-05-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='fitnessgoal',
            new_name='fitness_goals',
        ),
        migrations.AddField(
            model_name='userdata',
            name='fitness_plan',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
