# Generated by Django 5.0.6 on 2024-05-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_rename_fitnessgoal_userdata_fitness_goals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='fitness_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='meal_plan',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
